# Generated by Django 5.2.9 on 2025-12-19 12:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên rạp')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rạp chiếu',
                'verbose_name_plural': 'Rạp chiếu phim',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại phim',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên phim')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('director', models.CharField(max_length=100, verbose_name='Đạo diễn')),
                ('cast', models.TextField(verbose_name='Diễn viên')),
                ('duration', models.IntegerField(verbose_name='Thời lượng (phút)')),
                ('release_date', models.DateField(verbose_name='Ngày khởi chiếu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc chiếu')),
                ('country', models.CharField(max_length=100, verbose_name='Quốc gia')),
                ('language', models.CharField(max_length=50, verbose_name='Ngôn ngữ')),
                ('rating', models.CharField(choices=[('P', 'P - Phim dành cho mọi đối tượng'), ('K', 'K - Phim dành cho người dưới 13 tuổi với sự hướng dẫn của phụ huynh'), ('T13', 'T13 - Phim dành cho khán giả từ đủ 13 tuổi trở lên'), ('T16', 'T16 - Phim dành cho khán giả từ đủ 16 tuổi trở lên'), ('T18', 'T18 - Phim dành cho khán giả từ đủ 18 tuổi trở lên'), ('C', 'C - Phim cấm chiếu')], max_length=3, verbose_name='Phân loại')),
                ('poster', models.ImageField(upload_to='movies/posters/', verbose_name='Poster')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Link trailer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang chiếu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre', verbose_name='Thể loại')),
            ],
            options={
                'verbose_name': 'Phim',
                'verbose_name_plural': 'Phim',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên phòng')),
                ('screen_type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX')], default='2D', max_length=10, verbose_name='Loại phòng')),
                ('total_seats', models.IntegerField(verbose_name='Tổng số ghế')),
                ('rows', models.IntegerField(verbose_name='Số hàng ghế')),
                ('seats_per_row', models.IntegerField(verbose_name='Số ghế mỗi hàng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.cinema', verbose_name='Rạp')),
            ],
            options={
                'verbose_name': 'Phòng chiếu',
                'verbose_name_plural': 'Phòng chiếu',
                'unique_together': {('cinema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2, verbose_name='Hàng')),
                ('number', models.IntegerField(verbose_name='Số ghế')),
                ('seat_type', models.CharField(choices=[('STANDARD', 'Ghế thường'), ('VIP', 'Ghế VIP'), ('COUPLE', 'Ghế đôi')], default='STANDARD', max_length=10, verbose_name='Loại ghế')),
                ('is_active', models.BooleanField(default=True, verbose_name='Có thể đặt')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.screen', verbose_name='Phòng chiếu')),
            ],
            options={
                'verbose_name': 'Ghế',
                'verbose_name_plural': 'Ghế ngồi',
                'ordering': ['row', 'number'],
                'unique_together': {('screen', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Giờ chiếu')),
                ('end_time', models.DateTimeField(verbose_name='Giờ kết thúc')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá vé cơ bản')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie', verbose_name='Phim')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.screen', verbose_name='Phòng chiếu')),
            ],
            options={
                'verbose_name': 'Suất chiếu',
                'verbose_name_plural': 'Suất chiếu',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=20, unique=True, verbose_name='Mã đặt vé')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy'), ('EXPIRED', 'Hết hạn')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Phương thức thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đặt')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('expires_at', models.DateTimeField(verbose_name='Hết hạn lúc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người đặt')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.showtime', verbose_name='Suất chiếu')),
            ],
            options={
                'verbose_name': 'Đơn đặt vé',
                'verbose_name_plural': 'Đơn đặt vé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('comment', models.TextField(verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie', verbose_name='Phim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá phim',
                'ordering': ['-created_at'],
                'unique_together': {('movie', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đặt')),
                ('expires_at', models.DateTimeField(verbose_name='Hết hạn lúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang giữ chỗ')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.booking', verbose_name='Đơn hàng')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.seat', verbose_name='Ghế')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đặt')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.showtime', verbose_name='Suất chiếu')),
            ],
            options={
                'verbose_name': 'Ghế đã đặt',
                'verbose_name_plural': 'Ghế đã đặt',
                'unique_together': {('showtime', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá vé')),
                ('is_used', models.BooleanField(default=False, verbose_name='Đã sử dụng')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian sử dụng')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='movies.booking', verbose_name='Đơn hàng')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.seat', verbose_name='Ghế')),
            ],
            options={
                'verbose_name': 'Vé',
                'verbose_name_plural': 'Vé xem phim',
                'unique_together': {('booking', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('STANDARD', 'Ghế thường'), ('VIP', 'Ghế VIP'), ('COUPLE', 'Ghế đôi')], max_length=10, verbose_name='Loại ghế')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá vé')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_prices', to='movies.showtime', verbose_name='Suất chiếu')),
            ],
            options={
                'verbose_name': 'Giá vé',
                'verbose_name_plural': 'Bảng giá vé',
                'unique_together': {('showtime', 'seat_type')},
            },
        ),
    ]
